/**:
  ros__parameters:
    rs6_mesh_resource: "package://scooping_controller/models/scooping_container/meshes/rs6_container.STL"
    rs6_position_xyz: [0.460, -0.119, 0.00]
    rs6_orientation_xyzw: [0.0, 0.0, 1.0, 0.0]
    rs6_scale_xyz: [0.001, 0.001, 0.001]
    rs6_color_rgb: [0.7, 0.7, 0.7]

    rs3_mesh_resource: "package://scooping_controller/models/weighing_container/meshes/rs3_container.STL"
    rs3_position_xyz: [0.00, -0.4218, 0.07]
    rs3_orientation_xyzw: [0.0, 0.0, 0.70710678, 0.70710678]
    rs3_scale_xyz: [0.001, 0.001, 0.001]
    rs3_color_rgb: [0.4, 0.8, 0.4]

    table_geometry_type: "box"
    table_mesh_resource: ""
    table_position_xyz: [0.00, 0.00, -0.02]
    table_orientation_xyzw: [0.0, 0.0, 0.0, 1.0]
    table_scale_xyz: [1.0, 1.0, 1.0]
    table_dimensions_xyz: [1.02, 0.61, 0.03]
    table_color_rgb: [0.55, 0.39, 0.22]
