/**:
  ros__parameters:
    scooping_container_mesh_resource: "package://scooping_controller/models/scooping_container/meshes/container.STL"
    scooping_container_position_xyz: [0.10, -0.30, 0.00]
    scooping_container_orientation_xyzw: [0.0, 0.0, 0.0, 1.0]
    scooping_container_scale_xyz: [0.0004, 0.0004, 0.0003]
    scooping_container_color_rgb: [0.7, 0.7, 0.7]

    weighing_container_mesh_resource: "package://scooping_controller/models/weighing_container/meshes/container.STL"
    weighing_container_position_xyz: [-0.075, -0.40, 0.00]
    weighing_container_orientation_xyzw: [0.0, 0.0, -0.70710678, 0.70710678]
    weighing_container_scale_xyz: [0.0001, 0.0001, 0.0001]
    weighing_container_color_rgb: [0.4, 0.8, 0.4]
