global:
  scrape_interval: 30s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["127.0.0.1:9093"]

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["127.0.0.1:9091"]

  - job_name: node
    file_sd_configs:
      - files:
          - /etc/prometheus/targets-node.json
        refresh_interval: 1m

  - job_name: cadvisor
    file_sd_configs:
      - files:
          - /etc/prometheus/targets-cadvisor.json
        refresh_interval: 1m
